# Generated by Django 5.2.16 on 2026-07-13 14:24

import django.db.models.deletion
import shared.utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('hod', 'Head of Department'), ('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('lab_assistant', 'Lab Assistant'), ('visiting_faculty', 'Visiting Faculty')], default='lecturer', max_length=30)),
                ('joining_date', models.DateField()),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('publications', models.TextField(blank=True)),
                ('research_area', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('retired', 'Retired'), ('resigned', 'Resigned')], db_index=True, default='active', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('office_room', models.CharField(blank=True, max_length=50)),
                ('office_hours', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='faculty/documents/%Y/%m/', validators=[shared.utils.validators.DocumentValidator()])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='faculty/images/%Y/%m/', validators=[shared.utils.validators.ImageValidator(max_size=2097152)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_members', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Profile',
                'verbose_name_plural': 'Faculty Profiles',
                'db_table': 'faculty_faculty_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='faculty.facultyprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_subjects', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Faculty Subject Assignment',
                'verbose_name_plural': 'Faculty Subject Assignments',
                'db_table': 'faculty_faculty_subject',
            },
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['employee_id', 'status'], name='faculty_fac_employe_91fa55_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['department', 'status'], name='faculty_fac_departm_79c6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['designation', 'status'], name='faculty_fac_designa_481ba6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facultysubject',
            unique_together={('faculty', 'subject', 'session')},
        ),
    ]
