# Generated by Django 5.2.16 on 2026-07-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department'),
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.course'),
        ),
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.course'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('session', 'course', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('course', 'code')},
        ),
    ]
