# Generated by Django 5.2.16 on 2026-07-13 14:24

import django.db.models.deletion
import shared.utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('roll_number', models.CharField(db_index=True, max_length=20)),
                ('admission_date', models.DateField()),
                ('category', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('passed_out', 'Passed Out'), ('transferred', 'Transferred'), ('suspended', 'Suspended'), ('expelled', 'Expelled')], db_index=True, default='active', max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('aadhaar_number', models.CharField(blank=True, db_index=True, max_length=12)),
                ('scholarship_status', models.BooleanField(default=False)),
                ('fee_waiver', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.course')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.semester')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'students_student_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('photo', 'Passport Photo'), ('signature', 'Signature'), ('tenth_marksheet', '10th Marksheet'), ('twelfth_marksheet', '12th Marksheet'), ('domicile', 'Domicile Certificate'), ('caste_certificate', 'Caste Certificate'), ('income_certificate', 'Income Certificate'), ('transfer_certificate', 'Transfer Certificate'), ('character_certificate', 'Character Certificate'), ('medical_certificate', 'Medical Certificate'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='students/documents/%Y/%m/', validators=[shared.utils.validators.DocumentValidator(max_size=10485760)])),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'db_table': 'students_student_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('practical', 'Practical'), ('viva', 'Viva')], max_length=20)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('is_pass', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Examination Result',
                'verbose_name_plural': 'Examination Results',
                'db_table': 'students_examination_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR Scan'), ('face', 'Face Recognition'), ('biometric', 'Biometric')], default='manual', max_length=20)),
                ('qr_code_data', models.CharField(blank=True, db_index=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'students_attendance',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['enrollment_number', 'status'], name='students_st_enrollm_710826_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['course', 'status'], name='students_st_course__2980b8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['roll_number'], name='students_st_roll_nu_e2ecf0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='students_at_student_57d285_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['subject', 'date'], name='students_at_subject_6b2576_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['qr_code_data'], name='students_at_qr_code_45d85c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
    ]
