# Generated by Django 5.2.16 on 2026-07-13 14:24

import django.db.models.deletion
import django.utils.timezone
import shared.utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#0d6efd', max_length=7)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notice Category',
                'verbose_name_plural': 'Notice Categories',
                'db_table': 'notices_notice_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('publish_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/attachments/%Y/%m/', validators=[shared.utils.validators.DocumentValidator(max_size=10485760)])),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notices', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='notices.noticecategory')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'db_table': 'notices_notice',
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='NoticeReadReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='notices.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice Read Receipt',
                'verbose_name_plural': 'Notice Read Receipts',
                'db_table': 'notices_notice_read_receipt',
            },
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['category', 'is_active', 'publish_date'], name='notices_not_categor_1d7740_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['priority', 'is_active'], name='notices_not_priorit_f90a24_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['slug', 'is_active'], name='notices_not_slug_f258cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['publish_date', 'expiry_date'], name='notices_not_publish_1bb5a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noticereadreceipt',
            unique_together={('notice', 'user')},
        ),
    ]
